Music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music' #Namespace..to indicate that detail is a part of music app

urlpatterns = [
    #music/
    url(r'^$',views.index, name='index'),
    
    #music/<album_id>
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),
]

Website_django/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^music/', include('Music.urls')),
    url(r'^admin/', admin.site.urls),
]

Music/models.py
from django.db import models

#album1 has primary key 1(unique Id)
class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000) #album_logo will be linked to an URL, and Urls are quite big, so 1000
    
    #This function will print out the objects name on the database, or help filter out database results
    def __str__(self):
        return self.album_title + '-' + self.artist

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)  #Foreign key links to the primary key of Album
    song_title = models.CharField(max_length=500)
    file_type = models.CharField(max_length=10) #file extension
    
    def __str__(self):
        return self.song_title

Music/views.py
#from django.http import HttpResponse ... http response is inbuilt in render template shortcut

from django.http import Http404
from django.shortcuts import render, get_object_or_404
from .models import Album

def index(request):
    all_albums = Album.objects.all() #Connecting albums to the database
    #template = loader.get_template('music/index.html') ...used when we imported loader
    context = {
        'all_albums' : all_albums
    }
    #return HttpResponse(template.render(context, request))...used when we imported loader
    return render(request, 'music/index.html', context)

def detail(request,album_id):
    #try:
    #    album = Album.objects.get(pk=album_id)
    #except Album.DoesNotExist:
    #    raise Http404("Album does not exist")
    
    album = get_object_or_404(Album, pk=album_id)
    return render(request, 'music/detail.html', {'album' : album})

Music/templates/music/detail.html
<img src="album.album_logo">

<h1>{{album.album_title}}</h1>
<h3>{{album.artist}}</h3>

<ul>
    {% for song in album.song_set.all %}
        <li>{{song.song_title}} - {{song.file_type}}</li>
    {% endfor %}
 
</ul>

Music/templates/music/index.html
{% if all_albums %}
<h2>Here are all my albums</h2>

    <ul>
        {% for album in all_albums %}
        <li><a href = "{% url 'music:detail' album.id %}">{{album.album_title}}</a></li> 
        {% endfor %}
    </ul>
{% else %}
    <h3>You don't have any albums here.</h3>
{% endif %}